---
title: "G53FIV Coursework | PSYCX1 - 14331485"
output:
    pdf_document:
      latex_engine: xelatex
      includes:
        in_header: preamble.tex
      number_sections: true
geometry: "left=1.5cm,right=1.5cm,top=2cm,bottom=2cm"
classoption: twocolumn
header-includes:
    - \usepackage{charter} % Font
    - \setlength{\columnsep}{1cm}
    - \usepackage{booktabs}
    - \usepackage{sectsty} \sectionfont{\centering}
    - \usepackage{biblatex}
    - \addbibresource{bib.bib}
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
	message = FALSE,
	warning = TRUE,
	include = FALSE
)
library(scales) # Used for pretty
library(dplyr)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(here)
library(naniar)
library(countrycode)
library(stringr)
theme_set(theme_bw())
```

```{r load_data, include=FALSE}
df_raw_1 <- as_tibble(read_csv("data/wine_new.csv"))
df_raw_2 <- as_tibble(read_csv("data/wine.csv"))

df_2 <- select(df_raw_2, -c(X1, description, province, region_1, region_2,
                            taster_twitter_handle))

df_1 <- select(df_raw_1, -c(description, province, region_1, region_2,
                            taster_twitter_handle, taster_photo, vintage))

df <- df_1 %>% add_row(df_2) %>% distinct(title, .keep_all=TRUE) %>% 
  mutate(taster_name = gsub("\u00A0", " ", taster_name, fixed = TRUE)) %>% 
  mutate(taster_name = gsub("’", "\'", taster_name))

df$continent <- countrycode(sourcevar = pull(df, country),
                            origin = "country.name",
                            destination = "continent")

POINT_SIZE <-  3

# country = col_character(),
# designation = col_character(),
# points = col_double(),
# price = col_double(),
# taster_name = col_character(), 
# taster_twitter_handle = col_character(),
# title = col_character(),
# variety = col_character(),
# winery = col_character()
```

### EDA
```{r}
p_d <- ggplot(df)
p_d + geom_density(aes(x = log(price)))
p_d + geom_bar(aes(x = points))
```

### 1 - Which country's wines have been reviewed the most?
```{r}
df_1 <- df %>%
  drop_na(country) %>% 
  group_by(country, continent) %>%
  count(name = 'count') %>%
  ungroup() %>% 
  slice_max(count, n = 10)

p <- ggplot(df_1, aes(count, reorder(country, count),
                      color = continent))

p + geom_point(size=POINT_SIZE) +
  xlim(-500, 80500) + 
  labs(x = 'Count', y = NULL, color = 'Continent') + 
  theme(legend.position = "top")

ggsave('figures/1.jpg', width = 9, height = 6, scale = 0.75)
```


### 2 - From the most reviewed countries, which has the best reviews?
```{r}
df_2 <- df %>% 
  drop_na(country) %>% 
  group_by(country, continent) %>%
  summarize(points_mean = mean(points, na.rm = TRUE),
            points_sd = sd(points, na.rm = TRUE),
            count = n()) %>% 
  ungroup() %>%
  slice_max(count, n=10)

p <- ggplot(df_2, aes(points_mean, reorder(country, points_mean),
                      color = continent))

p + geom_pointrange(aes(xmin = points_mean - points_sd,
                        xmax = points_mean + points_sd),
                    alpha=0.30,
                    size = 1.50,
                    fatten = 0.01,
                    show.legend = FALSE) +
  geom_point(size = POINT_SIZE) +
  scale_x_continuous(limits = c(83,95),
                     expand = c(0,0.5),
                     breaks = pretty_breaks(n = 8)) +
  labs(x = 'Points', y = NULL, color = 'Continent') + 
  theme(legend.position = "top")

ggsave('figures/2.jpg', width = 10, height = 6, scale = 0.75)
```

### 3 - Which tasters are the harshest and the kindest?
```{r}
df_genders <- as_tibble(read_csv('data/taster_genders.csv'))

df_3 <- df %>%
  drop_na(taster_name) %>% 
  group_by(taster_name) %>%
  summarize(points_mean = mean(points, na.rm = TRUE),
            points_sd = sd(points, na.rm = TRUE),
            count = n()) %>%  
  left_join(df_genders, by='taster_name')

p <- ggplot(df_3, aes(points_mean, reorder(taster_name, points_mean),
                      color=gender))

p + geom_pointrange(aes(xmin = points_mean - points_sd,
                        xmax = points_mean + points_sd),
                    alpha=0.35,
                    size = 1,
                    fatten = 0.01,
                    show.legend = FALSE) + 
  geom_point() + 
  scale_x_continuous(limits = c(83,95),
                     expand = c(0,0.5),
                     breaks = pretty_breaks(n = 8)) +
  labs(x = 'Points', y = NULL, color = 'Gender') +  
  theme(legend.position = "top")

ggsave('figures/3.jpg', scale=0.75)
```


### 4 - Are pricier wines better?
```{r, fig.height=8, fig.width=8}
df_4 <- df %>% select(c(price, points))
  
p <- ggplot(df_4, aes(price, factor(points),
                      fill = ..x..))

p + geom_density_ridges_gradient(scale = 1.75,
                                 size = 0.25,
                                 rel_min_height = 0.01,
                                 quantile_lines=TRUE,
                                 quantile_fun=function(x,...)median(x)) +
  scale_fill_viridis_c(name = 'Log Price', option = 'D') +
  scale_x_log10(labels = scales::dollar, expand = c(0, 0)) +
  guides(fill=FALSE) + 
  labs(x = 'Price', y = 'Points')

ggsave('figures/4.jpg', scale=0.75)
### END OF QUESTION 3
```



### 5 - Which wines have the best value in terms of the price to points ratio?
```{r}
df_q5 <- df %>% 
  drop_na(price) %>% 
  drop_na(country) %>% 
  mutate(ppr = points / price)

df_q5.1 <- df_q5 %>% 
  filter(country %in% df_q1$country)

order <- df_q5.1 %>%
  group_by(country) %>%
  summarize(ppr_mean = mean(ppr, na.rm = TRUE)) %>% 
  arrange(ppr_mean) %>%
  pull(country)

p <- ggplot(df_q5.1, aes(ppr))
p + geom_density(size=0.3) +
  facet_wrap(~factor(df_q5.1$country, levels = order),
             nrow=2, ncol=5) +
  labs(x='Points to Price Ratio', y='Density') +
  scale_x_continuous(limits = c(0,18), expand = c(0, 0)) +
  scale_y_continuous(expand = c(0.05, 0))

ggsave('figures/5.1.jpg', height=8, width = 10, scale=0.75)
```
```{r}
df_q5.2 <- df_q5 %>% 
  slice_max(order_by=ppr, n=10)

p <- ggplot(df_q5.2, aes(ppr, reorder(title, ppr),
                         color=country))

p + geom_point() +
  geom_text(aes(label=points, hjust=-1, vjust=0.35),
            size=3.5,
            show.legend = FALSE) +
  scale_x_continuous(limits = c(20.65, 21.65)) +
  labs(x='PPR', y=NULL, color='Country')
  
ggsave('figures/5.2.jpg')
```

```{r}
df_q5.3 <- df_q5 %>% 
  filter(points >= 94) %>%
  slice_max(order_by=ppr, n=10)


p <- ggplot(df_q5.3, aes(ppr, reorder(title, ppr), color=country))
p + geom_point() +
  geom_text(aes(label=points, hjust=-1, vjust=0.35),
            size=3.5,
            show.legend = FALSE) +
  scale_x_continuous(expand = c(0.25,0), breaks = scales::pretty_breaks(n = 4)) +
  labs(x='PPR', y=NULL, color='Country')

ggsave('figures/5.3.jpg')
  
```
### Question 6 - Does does wine consumption increase with wine production?
```{r}
# df_6 <- as_tibble(read_csv('data/alcohol_consumption_per_capita.csv')) %>% 
#   select(c('Country Name', '2015 [YR2015]', '2018 [YR2018]')) %>% 
#   rename(country = 'Country Name',
#          yr_2015 = '2015 [YR2015]',
#          yr_2018 = '2018 [YR2018]') %>% 
#   naniar::replace_with_na_all(condition = ~ .x == '..') %>% 
#   drop_na()

df_consumption <- as_tibble(read_delim('data/consumption.csv', ';')) %>% 
  select(Continent, Country, Value) %>% 
  rename(continent = Continent, country = Country, consumption_capita_l = Value)
df_production <- as_tibble(read_delim('data/production.csv', ';')) %>%
  select(Country, Value) %>% 
  rename(country = Country,
         production_1000_hl = Value)
df_pop <- as_tibble(read_csv('data/population_data.csv', skip=4)) %>%
  select('Country Name', '2016') %>% 
  rename(country = 'Country Name',
         population = '2016')
```
```{r}
df_6 <- df_production %>%
  left_join(df_pop, by = 'country') %>% 
  left_join(df_consumption, by='country') %>% 
  drop_na() %>% 
  mutate(production_capita_l = production_1000_hl * 1000 * 100 / population) # Converting from 1000 hectoliters to liters
```

```{r}
p <- ggplot(df_6, aes(production_capita_l, consumption_capita_l))

p + geom_line(stat="smooth",method = "gam", colour='tomato',
              size = 0.8,
              alpha = 0.80) + 
  # geom_abline(intercept = 0,
  #             slope = 1,
  #             color = 'black',
  #             linetype="dashed",
  #             size=0.5,
  #             alpha=0.5) +
  geom_point(aes(color = continent), size = 2, alpha = 0.50) +
  labs(x='Production per capita (liters)', y = 'Consumption per capita (liters)', color='Continent') +
  theme(legend.position = "top")

ggsave('figures/6.jpg', height=6, width=9, scale = 0.75)
```